name: 'deadnix-action'
description: 'Find unused Nix code, and create a pull request'
inputs:
  flags:
    description: 'Command-line flags to deadnix'
    required: false
    default: '--edit'
  author:
    description: >
      The author name and email address in the format `Display Name <email@address.com>`.
      Defaults to the user who triggered the workflow run.
    required: false
    default: '${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>'
  committer:
    description: >
      The committer name and email address in the format `Display Name <email@address.com>`.
      Defaults to the GitHub Actions bot user.
    default: 'GitHub <noreply@github.com>'
  directory:
    description: 'Command-line flags to deadnix'
    required: false
    default: '.'
  create_pr:
    description: 'Whether to create a PR'
    required: false
    default: 'true'
  commit_message:
    description: 'Commit message'
    required: false
    default: 'Remove dead code'
runs:
  using: 'composite'
  steps:
    - name: Nix dead code analysis
      run: 'nix run nixpkgs#deadnix -- ${{ inputs.flags }} ${{ inputs.directory }}'
      shell: bash
      id: deadnix
    - name: Create PR
      uses: peter-evans/create-pull-request@v5
      if: inputs.create_pr == 'true'
      with:
        author: '${{ inputs.author }}'
        branch: deadnix
        base: ${{ github.head_ref }}
        delete-branch: true
        title: '${{ inputs.commit_message }}'
        commit-message: '${{ inputs.commit_message }}'
        committer: '${{ inputs.committer }}'
        body: |
          Automated changes by the [deadnix-action](https://github.com/astro/deadnix-action) GitHub Action.
branding:
  icon: 'minus-circle'
  color: 'red'
